from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, SetEnvironmentVariable
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        SetEnvironmentVariable("PYTHONNOUSERSITE", "1"),
        DeclareLaunchArgument("px4_ns", default_value="/px4_1"),
        DeclareLaunchArgument("scan_topic", default_value="/ugv/lidar/scan"),
        DeclareLaunchArgument("marker_frame", default_value="odom"),
        DeclareLaunchArgument("goal_source", default_value="manual"),
        DeclareLaunchArgument("manual_goal_frame", default_value="relative"),
        DeclareLaunchArgument("heading_source", default_value="course"),
        DeclareLaunchArgument("goal_north", default_value="0.0"),
        DeclareLaunchArgument("goal_east", default_value="0.0"),
        DeclareLaunchArgument("goal_tolerance", default_value="1.0"),
        DeclareLaunchArgument("local_target_distance", default_value="1.5"),
        DeclareLaunchArgument("desired_speed", default_value="0.8"),
        DeclareLaunchArgument("max_speed", default_value="1.2"),
        DeclareLaunchArgument("slowdown_distance", default_value="2.0"),
        DeclareLaunchArgument("min_turn_speed_scale", default_value="0.25"),
        DeclareLaunchArgument("max_steering_angle", default_value="0.75"),
        DeclareLaunchArgument("turn_slowdown_angle", default_value="1.2"),
        DeclareLaunchArgument("obstacle_range", default_value="1.5"),
        DeclareLaunchArgument("stop_range", default_value="0.45"),
        DeclareLaunchArgument("avoid_gain", default_value="1.4"),
        DeclareLaunchArgument("front_fov_deg", default_value="180.0"),
        DeclareLaunchArgument("lidar_yaw_offset", default_value="0.0"),
        DeclareLaunchArgument("avoidance_corridor_deg", default_value="70.0"),
        DeclareLaunchArgument("avoidance_side_bias", default_value="3.2"),
        DeclareLaunchArgument("scan_timeout", default_value="0.6"),
        DeclareLaunchArgument("course_timeout", default_value="1.0"),
        DeclareLaunchArgument("course_min_distance", default_value="0.02"),
        DeclareLaunchArgument("allow_reverse", default_value="false"),
        DeclareLaunchArgument("publish_trajectory_setpoint", default_value="false"),
        DeclareLaunchArgument("publish_rover_setpoints", default_value="true"),
        DeclareLaunchArgument("rover_yaw_offset", default_value="0.0"),
        DeclareLaunchArgument("rover_steering_sign", default_value="-1.0"),
        DeclareLaunchArgument("auto_offboard", default_value="false"),
        DeclareLaunchArgument("auto_arm", default_value="false"),
        DeclareLaunchArgument("target_system", default_value="2"),
        DeclareLaunchArgument("use_sim_time", default_value="false"),
        Node(
            package="ugv_description",
            executable="lidar_local_planner_node",
            name="lidar_local_planner",
            output="screen",
            parameters=[{
                "px4_ns": LaunchConfiguration("px4_ns"),
                "scan_topic": LaunchConfiguration("scan_topic"),
                "marker_frame": LaunchConfiguration("marker_frame"),
                "goal_source": LaunchConfiguration("goal_source"),
                "manual_goal_frame": LaunchConfiguration("manual_goal_frame"),
                "heading_source": LaunchConfiguration("heading_source"),
                "goal_north": LaunchConfiguration("goal_north"),
                "goal_east": LaunchConfiguration("goal_east"),
                "goal_tolerance": LaunchConfiguration("goal_tolerance"),
                "local_target_distance": LaunchConfiguration("local_target_distance"),
                "desired_speed": LaunchConfiguration("desired_speed"),
                "max_speed": LaunchConfiguration("max_speed"),
                "slowdown_distance": LaunchConfiguration("slowdown_distance"),
                "min_turn_speed_scale": LaunchConfiguration("min_turn_speed_scale"),
                "max_steering_angle": LaunchConfiguration("max_steering_angle"),
                "turn_slowdown_angle": LaunchConfiguration("turn_slowdown_angle"),
                "obstacle_range": LaunchConfiguration("obstacle_range"),
                "stop_range": LaunchConfiguration("stop_range"),
                "avoid_gain": LaunchConfiguration("avoid_gain"),
                "front_fov_deg": LaunchConfiguration("front_fov_deg"),
                "lidar_yaw_offset": LaunchConfiguration("lidar_yaw_offset"),
                "avoidance_corridor_deg": LaunchConfiguration("avoidance_corridor_deg"),
                "avoidance_side_bias": LaunchConfiguration("avoidance_side_bias"),
                "scan_timeout": LaunchConfiguration("scan_timeout"),
                "course_timeout": LaunchConfiguration("course_timeout"),
                "course_min_distance": LaunchConfiguration("course_min_distance"),
                "allow_reverse": LaunchConfiguration("allow_reverse"),
                "publish_trajectory_setpoint": LaunchConfiguration("publish_trajectory_setpoint"),
                "publish_rover_setpoints": LaunchConfiguration("publish_rover_setpoints"),
                "rover_yaw_offset": LaunchConfiguration("rover_yaw_offset"),
                "rover_steering_sign": LaunchConfiguration("rover_steering_sign"),
                "auto_offboard": LaunchConfiguration("auto_offboard"),
                "auto_arm": LaunchConfiguration("auto_arm"),
                "target_system": LaunchConfiguration("target_system"),
                "use_sim_time": LaunchConfiguration("use_sim_time"),
            }],
        ),
    ])
